# fly.toml app configuration file generated for gamejam-homepage-superfine on 2023-09-22T10:49:46+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gamejam-homepage-superfine"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
